params:
  seed: 8
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  load_checkpoint: False

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [64,32]
      d2rl: False
      activation: relu
      initializer:
        name: default
        scale: 2
  config:
    env_name: position_setpoint_task_trirotor_6d
    env_config:
      num_envs: 32

    name: trirotor_6d
    reward_shaper:
      scale_value: 0.1

    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    ppo: True
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.02
    save_best_after: 5
    score_to_win: 100000
    grad_norm: 1.0
    entropy_coef: 0.0001
    truncate_grads: True
    e_clip: 0.2
    clip_value: False
    num_actors: 32
    horizon_length: 32
    minibatch_size: 1024   # must be divisible by num_actors*horizon_length (=1024 for defaults)
    mini_epochs: 4
    critic_coef: 2
    normalize_input: False
    bounds_loss_coef: 0.0001
    max_epochs: 1000
    normalize_value: True
    use_diagnostics: True
    value_bootstrap: True
    use_smooth_clamp: False

    player:
      render: True
      deterministic: True
      games_num: 1000

